{
  description = "Nexterm is an open-source server management software";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; };
        version = (builtins.fromJSON (builtins.readFile ./package.json)).version;
        nodejs = pkgs.nodejs_26;

        # Regenerated by .github/workflows/nix-update.yml whenever a yarn.lock changes.
        yarnHashes = builtins.fromJSON (builtins.readFile ./nix/yarn-hashes.json);

        clientOfflineCache = pkgs.fetchYarnDeps {
          yarnLock = ./client/yarn.lock;
          sha256 = yarnHashes.client;
        };
        rootOfflineCache = pkgs.fetchYarnDeps {
          yarnLock = ./yarn.lock;
          sha256 = yarnHashes.root;
        };

        client = pkgs.stdenv.mkDerivation {
          pname = "nexterm-client";
          inherit version;
          src = self;
          nativeBuildInputs = [ nodejs pkgs.yarn pkgs.fixup-yarn-lock pkgs.autoPatchelfHook ];
          buildInputs = [ pkgs.stdenv.cc.cc.lib ];
          dontAutoPatchelf = true;
          configurePhase = ''
            runHook preConfigure
            export HOME=$(mktemp -d)
            export ESBUILD_BINARY_PATH=${pkgs.esbuild}/bin/esbuild
            yarn config --offline set yarn-offline-mirror ${clientOfflineCache}
            pushd client
              fixup-yarn-lock yarn.lock
              yarn install --offline --frozen-lockfile --ignore-scripts --no-progress --non-interactive
            popd
            patchShebangs client/node_modules
            autoPatchelf client/node_modules || true
            runHook postConfigure
          '';
          buildPhase = ''
            runHook preBuild
            pushd client && yarn --offline build && popd
            runHook postBuild
          '';
          installPhase = ''
            runHook preInstall
            cp -r client/dist $out
            runHook postInstall
          '';
        };

        nexterm = pkgs.stdenv.mkDerivation {
          pname = "nexterm";
          inherit version;
          src = self;
          nativeBuildInputs = [
            nodejs pkgs.yarn pkgs.fixup-yarn-lock pkgs.flatbuffers pkgs.esbuild
            pkgs.makeWrapper pkgs.python3 pkgs.pkg-config pkgs.autoPatchelfHook
          ];
          buildInputs = [ pkgs.stdenv.cc.cc.lib ];
          dontAutoPatchelf = true;
          configurePhase = ''
            runHook preConfigure
            export HOME=$(mktemp -d)
            yarn config --offline set yarn-offline-mirror ${rootOfflineCache}
            fixup-yarn-lock yarn.lock
            yarn install --offline --frozen-lockfile --production --ignore-scripts --no-progress --non-interactive
            patchShebangs node_modules
            runHook postConfigure
          '';
          buildPhase = ''
            runHook preBuild
            export npm_config_nodedir=${nodejs}
            npm rebuild --build-from-source bcrypt sqlite3
            autoPatchelf node_modules || true
            flatc --ts --ts-flat-files -o server/lib/generated schema/control_plane.fbs schema/sftp_protocol.fbs
            esbuild server/lib/generated/nexterm/control-plane.ts --bundle --format=cjs --outfile=server/lib/generated/control_plane_generated.js --platform=node --external:flatbuffers
            esbuild server/lib/generated/nexterm/sftp-protocol.ts --bundle --format=cjs --outfile=server/lib/generated/sftp_protocol_generated.js --platform=node --external:flatbuffers
            rm -rf server/lib/generated/nexterm
            runHook postBuild
          '';
          installPhase = ''
            runHook preInstall
            mkdir -p $out/lib/nexterm
            cp -r server package.json node_modules $out/lib/nexterm/
            cp -r ${client} $out/lib/nexterm/dist
            mkdir -p $out/lib/nexterm/data
            chmod -R u+w $out/lib/nexterm
            makeWrapper ${nodejs}/bin/node $out/bin/nexterm \
              --add-flags "$out/lib/nexterm/server/index.js" \
              --set NODE_ENV production
            runHook postInstall
          '';
        };

        engine = pkgs.stdenv.mkDerivation {
          pname = "nexterm-engine";
          inherit version;
          src = self;
          nativeBuildInputs = [ pkgs.cmake pkgs.pkg-config pkgs.flatcc pkgs.autoPatchelfHook pkgs.makeWrapper ];
          buildInputs = [
            pkgs.guacamole-server pkgs.freerdp pkgs.libvncserver pkgs.libssh2
            pkgs.curl pkgs.openssl pkgs.libwebp pkgs.cairo pkgs.pango pkgs.libjpeg
            pkgs.stdenv.cc.cc.lib
          ];
          configurePhase = ''
            runHook preConfigure
            mkdir -p vendor/guacamole-server/dist
            ln -sfn ${pkgs.guacamole-server}/include vendor/guacamole-server/dist/include
            ln -sfn ${pkgs.guacamole-server}/lib vendor/guacamole-server/dist/lib
            cmake -S engine -B build -DCMAKE_BUILD_TYPE=Release \
              -DFLATCC_EXECUTABLE=${pkgs.flatcc}/bin/flatcc \
              -DFLATCC_INCLUDE_DIR=${pkgs.flatcc}/include \
              -DFLATCC_LIB_DIR=${pkgs.flatcc}/lib
            runHook postConfigure
          '';
          buildPhase = ''
            runHook preBuild
            cmake --build build -j$NIX_BUILD_CORES
            runHook postBuild
          '';
          installPhase = ''
            runHook preInstall
            install -Dm755 build/nexterm-engine $out/libexec/nexterm-engine
            makeWrapper $out/libexec/nexterm-engine $out/bin/nexterm-engine \
              --prefix LD_LIBRARY_PATH : ${pkgs.guacamole-server}/lib
            runHook postInstall
          '';
          preFixup = ''
            patchelf --remove-rpath $out/libexec/nexterm-engine || true
          '';
        };
      in {
        packages.client = client;
        packages.nexterm = nexterm;
        packages.engine = engine;
        packages.default = nexterm;

        devShells.default = pkgs.mkShell {
          name = "nexterm-dev";
          packages = with pkgs; [
            nodejs_26 yarn flatbuffers flatcc cmake pkg-config
            freerdp libvncserver libssh2 curl openssl libwebp cairo libjpeg pango guacamole-server
          ];
        };
      }) // {
      nixosModules.default = import ./nix/module.nix self;
    };
}
