name: nexterm
description: "The open source server management software for SSH, VNC & RDP"
publish_to: 'none'
version: 1.2.0+9

environment:
  sdk: ^3.9.2

platforms:
  android:
  ios:

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  xterm: ^4.0.0
  shared_preferences: ^2.3.4
  http: ^1.2.0
  web_socket_channel: ^3.0.1
  google_fonts: ^6.2.1
  material_design_icons_flutter: ^7.0.7296
  url_launcher: ^6.2.5
  dynamic_color: ^1.8.1
  native_glass_navbar: ^1.0.1
  guacamole_common_dart:
    path: packages/guacamole_common_dart
  file_picker: ^8.0.0
  path_provider: ^2.1.5
  share_plus: ^12.0.2
  open_filex: ^4.6.0
  speech_to_text: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - favicon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "favicon.png"
  image_path_ios: "assets/icons/ios_app_icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "favicon.png"
  min_sdk_android: 21
  adaptive_icon_padding: 10
