export const Permission = Object.freeze({
    USERS_VIEW: "users.view",
    USERS_MANAGE: "users.manage",
    USERS_IMPERSONATE: "users.impersonate",
    PERMISSIONS_MANAGE: "permissions.manage",
    ORGANIZATIONS_CREATE: "organizations.create",
    ORGANIZATIONS_MANAGE_ALL: "organizations.manage_all",
    AUDIT_VIEW: "audit.view",
    SETTINGS_AUTH_PROVIDERS: "settings.auth_providers",
    SETTINGS_SOURCES: "settings.sources",
    SETTINGS_ENGINES: "settings.engines",
    SETTINGS_MONITORING: "settings.monitoring",
    SETTINGS_BACKUP: "settings.backup",
    SETTINGS_AI: "settings.ai",

    RESOURCES_MANAGE: "resources.manage",
    IDENTITIES_MANAGE: "identities.manage",
    SNIPPETS_MANAGE: "snippets.manage",
    SCRIPTS_MANAGE: "scripts.manage",
    CONNECT_SSH: "connect.ssh",
    CONNECT_RDP: "connect.rdp",
    CONNECT_VNC: "connect.vnc",
    CONNECT_PROXMOX: "connect.proxmox",
    CONNECT_TUNNEL: "connect.tunnel",
    FILES_VIEW: "files.view",
    FILES_UPLOAD: "files.upload",
    FILES_DOWNLOAD: "files.download",
    FILES_MODIFY: "files.modify",
    SCRIPTS_EXECUTE: "scripts.execute",

    ORG_MANAGE: "org.manage",
    ORG_DELETE: "org.delete",
    ORG_MEMBERS_MANAGE: "org.members.manage",
    ORG_AUDIT_VIEW: "org.audit.view",
    ORG_AUDIT_RECORDINGS: "org.audit.recordings",
});
